name: rasterio
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.2
  - altair=3.1.0
  - appdirs=1.4.3
  - appnope=0.1.0
  - asciitree=0.3.3
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.1
  - bleach=3.1.0
  - bokeh=1.2.0
  - boost-cpp=1.70.0
  - boto3=1.9.181
  - botocore=1.12.181
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2019.6.16
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.1
  - cryptography=2.7
  - curl=7.64.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=2.0.0
  - dask-core=2.0.0
  - dask-labextension=0.3.3
  - decorator=4.4.0
  - defusedxml=0.5.0
  - deprecated=1.2.5
  - descartes=1.1.0
  - distributed=2.0.1
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.5
  - fasteners=0.14.1
  - fiona=1.8.6
  - folium=0.9.1
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.1
  - geographiclib=1.49
  - geojson=2.4.1
  - geopandas=0.5.0
  - geopy=1.20.0
  - geos=3.7.1
  - geotiff=1.4.2
  - geoviews-core=1.6.2
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - holoviews=1.12.3
  - hvplot=0.4.0
  - icu=58.2
  - idna=2.8
  - intake=0.5.1
  - intake-xarray=0.3.0
  - ipykernel=5.1.1
  - ipyleaflet=0.11.1
  - ipython=7.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - jedi=0.14.0
  - jinja2=2.10.1
  - jmespath=0.9.4
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.8.4
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=1.0.0
  - jupyterlab_server=1.0.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libcurl=7.64.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.4.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.3
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - locket=0.2.0
  - lz4-c=1.8.3
  - mapclassify=2.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - monotonic=1.5
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.6.1
  - munch=2.3.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - networkx=2.3
  - nodejs=11.14.0
  - nomkl=3.0
  - notebook=5.7.8
  - numcodecs=0.6.3
  - numpy=1.16.1
  - olefile=0.46
  - openblas=0.3.3
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - osmnx=0.10
  - owslib=0.18.0
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - param=1.9.1
  - parso=0.5.0
  - partd=1.0.0
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.3
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.4.2
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyrsistent=0.15.2
  - pyshp=2.1.0
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.7.5
  - python-snappy=0.5.4
  - pytz=2019.1
  - pyviz_comms=0.7.2
  - pyyaml=5.1.1
  - pyzmq=18.0.2
  - rasterio=1.0.24
  - rasterstats=0.13.1
  - readline=7.0
  - requests=2.22.0
  - rtree=0.8.3
  - ruamel=1.0
  - ruamel.yaml=0.15.96
  - s3fs=0.2.2
  - s3transfer=0.2.1
  - sat-search=0.2.1
  - sat-stac=0.1.3
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - simplejson=3.16.0
  - six=1.12.0
  - snappy=1.1.7
  - snuggs=1.4.6
  - sortedcontainers=2.1.0
  - sqlite=3.28.0
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2019a
  - urllib3=1.24.3
  - vincent=0.4.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - wrapt=1.11.2
  - xarray=0.12.2
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.3.2
  - zeromq=4.3.1
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.4.0
prefix: /Users/scott/miniconda3/envs/rasterio
